services:
  database: 
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: TESTING_DATABASE
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASSWORD
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${SCHEMA_DIR}/:/docker-entrypoint-initdb.d:ro
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - label:disable
    network_mode: host
